#TLS Config YAML
tlsConfig :

  tlsCertPath : "valid_cert_file"

  tlsKeyPath : "valid_key_file"

  serverName : "localhost:1234"

  clientAuth : "RequireAndVerifyClientCert"

  clientCAs : "valid_ca_file"
